name: merkaartor
base: core22
version: '0.20.0'
summary: An OpenStreetMap editor
description: |
  Merkaartor is an OpenStreetMap editor for Linux, macOS and Windows.

grade: stable
confinement: strict
license: GPL-2.0
compression: lzo

parts:
  merkaartor:
    plugin: cmake
    source: https://github.com/openstreetmap/merkaartor.git
    source-commit: f55c5669b96bc5fa7ee309f3bd9145fb3c70d521 # 0.20.0
    cmake-parameters:
      - -DZBAR=ON
      - -DGPSD=OFF
      - -DWEBENGINE=ON
      - -DEXTRA_TESTS=OFF
      - -DCMAKE_BUILD_TYPE=Release
    build-snaps:
      - cmake
    build-packages:
      - build-essential
      - libgdal-dev
      - libproj-dev
      - libqt5svg5-dev
      - libexiv2-dev
      - libopengl-dev
      - libzbar-dev
      - libzbarqt-dev
      - libqoauth-dev
      - libprotobuf-dev
      - protobuf-compiler
    stage-packages:
      - libarmadillo10
      - libhdf4-0-alt
      - libgdal30
      - libhdf4-0-alt
      - libogdi4.1
      - libaec0
      - libarpack2
      - libblas3
      - libblosc1
      - libcfitsio9
      - libcharls2
      - libcurl4
      - libde265-0
      - libfreexl1
      - libfyba0
      - libgeos3.10.2
      - libgeos-c1v5
      - libgeotiff5
      - libgfortran5
      - libgif7
      - libhdf5-103-1
      - libhdf5-hl-100
      - libheif1
      - libkmlbase1
      - libkmldom1
      - libkmlengine1
      - liblapack3
      - libnetcdf19
      - libodbcinst2
      - libpoppler118
      - libproj22
      - libqhull-r8.0
      - libquadmath0
      - librttopo1
      - libspatialite7
      - libsuperlu5
      - libsz2
      - liburiparser1
      - libxerces-c3.2
      - libzbar0
      - libqoauth2
      - libprotobuf23
    organize:
      usr/lib/*-linux-gnu/blas/*: usr/lib/
      usr/lib/*-linux-gnu/lapack/*: usr/lib/

layout:
  /usr/local/lib/merkaartor/plugins:
    symlink: $SNAP/usr/local/lib/merkaartor/plugins

apps:
  merkaartor:
    command: usr/local/bin/merkaartor
    plugs:
      - network
      - home
      - unity7
      - removable-media
      - network-manager-observe
      - cups
      - avahi-control
      - network-manager
    extensions: [kde-neon]

