name: merkaartor-james-carroll
base: core18
version: '0.18.4'
summary: An OpenStreetMap editor
description: |
  Merkaartor is an OpenStreetMap editor for Linux, macOS and Windows, distributed under the GNU General Public License. 

grade: stable
confinement: strict
license: GPL-2.0
compression: lzo

parts:
  merkaartor:
    plugin: qmake
    source: https://github.com/openstreetmap/merkaartor.git
    source-tag: 0.18.4
    build-packages:
      - build-essential
      - libgdal-dev 
      - libproj-dev
      - libqt5svg5-dev
    build-snaps:
      - kde-frameworks-5-core18-sdk
      - kde-frameworks-5-core18
    stage-packages:
      - libglu1-mesa
      - libaec0
      - libarmadillo8
      - libarpack2
      - libdap25
      - libdapclient6v5
      - libepsilon1
      - libfreexl1
      - libfyba0
      - libgdal20
      - libgeos-3.6.2
      - libgeos-c1v5
      - libgeotiff2
      - libgfortran4
      - libgif7
      - libhdf4-0-alt
      - libhdf5-100
      - libkmlbase1
      - libkmldom1
      - libkmlengine1
      - libnetcdf13
      - libogdi3.2
      - libpoppler73
      - libproj12
      - libqhull7
      - libquadmath0
      - libspatialite7
      - libsuperlu5
      - libsz2
      - liburiparser1
      - libxerces-c3.2
      - odbcinst1debian2
      - libblas3
    organize:
      usr/lib/*-linux-gnu/blas/*: usr/lib/
      usr/lib/*-linux-gnu/lapack/*: usr/lib/
  cleanup:
    plugin: nil
    build-snaps:
      - core18
      - kde-frameworks-5-core18
    override-prime: |
      set -eux
      for snap in "core18" "kde-frameworks-5-core18"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
    after: [merkaartor]

apps:
  merkaartor:
    command: usr/local/bin/merkaartor
    plugs:
      - network
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - unity7
      - opengl
      - removable-media
      - network-manager-observe
      - cups-control
      - avahi-control
    extensions: [kde-neon]

