name: merkaartor-james-carroll
base: core20
version: '0.19.0'
summary: An OpenStreetMap editor
description: |
  Merkaartor is an OpenStreetMap editor for Linux, macOS and Windows, distributed under the GNU General Public License. 

grade: stable
confinement: strict
license: GPL-2.0
compression: lzo

parts:
  merkaartor:
    plugin: cmake
    source: https://github.com/openstreetmap/merkaartor.git
    source-tag: 0.19.0
    cmake-parameters:
      - -DZBAR=ON
      - -DGPSD=OFF
      - -DWEBENGINE=ON
      - -DEXTRA_TESTS=OFF
      - -DCMAKE_RELEASE_TYPE=Release
    build-snaps:
      - cmake
    build-packages:
      - build-essential
      - libgdal-dev 
      - libproj-dev
      - libqt5svg5-dev
      - libexiv2-dev
      - libopengl-dev
      - libzbar-dev
      - libzbarqt-dev
    stage-packages:
    stage-packages:
      - libaec0
      - libarmadillo9
      - libarpack2
      - libcfitsio8
      - libcharls2
      - libcurl3-gnutls
      - libdap25
      - libdapclient6v5
      - libepsilon1
      - libfreexl1
      - libfyba0
      - libgdal26
      - libgeos-3.8.0
      - libgeos-c1v5
      - libgeotiff5
      - libgfortran5
      - libgif7
      - libhdf4-0-alt
      - libhdf5-103
      - libkmlbase1
      - libkmldom1
      - libkmlengine1
      - libnetcdf15
      - libnghttp2-14
      - libogdi4.1
      - libproj15
      - libqhull7
      - libquadmath0
      - librtmp1
      - libspatialite7
      - libssh-4
      - libsuperlu5
      - libsz2
      - liburiparser1
      - libxerces-c3.2
      - libzbar0
      - odbcinst1debian2
    organize:
      usr/lib/*-linux-gnu/blas/*: usr/lib/
      usr/lib/*-linux-gnu/lapack/*: usr/lib/
  cleanup:
    plugin: nil
    build-snaps:
      - core18
      - kde-frameworks-5-core18
    override-prime: |
      set -eux
      for snap in "core20" "kde-frameworks-5-qt-5-15-3-core20"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
    after: [merkaartor]

layout:
  /usr/local/lib/merkaartor/plugins:
    symlink: $SNAP/usr/local/lib/merkaartor/plugins  

apps:
  merkaartor:
    command: usr/local/bin/merkaartor
    plugs:
      - network
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - unity7
      - opengl
      - removable-media
      - network-manager-observe
      - cups-control
      - avahi-control
      - network-manager
    extensions: [kde-neon]

