name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Name of the Git branch to build.'
        required: true
        default: 'main'
      release-channel:
        description: 'Channel on the Snap Store to push to (e.g: latest/stable/bug-fix)'
        required: true
        default: 'latest/beta'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref:  ${{ github.event.inputs.branch || 'main' }}
    - uses: snapcore/action-build@v1
      id: build
    - uses: actions/upload-artifact@v2
      with:
        name: 'merkaartor.snap'
        path: ${{ steps.build.outputs.snap}}
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: ${{ github.event.inputs.release-channel || 'latest/beta' }}
